### ISSUE TITLE
Improve tracking

### ISSUE THREAD

**Issue by stylesuxx** [stylesuxx/esc-configurator#82]
Send payloads with some of the Events:
* [x] When connected, add MSP and board Info
* [x] When Reading ESC's, add currently flashehd FW, version and Layout
* [x] When flashing, add information about what is being flashed
* [x] Publish in GTM
